# File: .github/workflows/frontend.yml
name: Frontend CI/CD 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Build Docker image
      run: docker build -t js-frontend-image .

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag js-frontend-image ${{ secrets.DOCKER_USERNAME }}/js-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/js-frontend:latest
